apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/namespace.yaml
  - ../base/mongodb.yaml
  - ../base/kafka.yaml
  - ../base/user-management.yaml
  - ../base/inventory.yaml
  - ../base/sales.yaml
  - ../base/financial.yaml
  - ../base/dashboard.yaml
  - ../base/gateway.yaml
  - ../base/frontend.yaml
  - ../base/prometheus.yaml
  - ../base/grafana.yaml

namespace: erp-local
